// Projectile
export const CREATE_PROJECTILE = 'CREATE_PROJECTILE';
export const GET_PROJECTILE = 'GET_PROJECTILE';
export const GET_PROJECTILE_SUCCESS = 'GET_PROJECTILE_SUCCESS';
export const GET_PROJECTILE_FAILED = 'GET_PROJECTILE_FAILED';
export const DELETE_PROJECTILE = 'DELETE_PROJECTILE';
export const EDIT_PROJECTILE = 'EDIT_PROJECTILE';
export const EDIT_PROJECTILE_FAILED = 'EDIT_PROJECTILE_FAILED';
export const GET_PROJECTILES = 'GET_PROJECTILES';
export const GET_PROJECTILES_SUCCESS = 'GET_PROJECTILES_SUCCESS';
export const DELETE_PROJECTILES = 'DELETE_PROJECTILES';
